name: Auto Build

on:
  push:
    branches:
      - "main"
    tags:
      - "[0-9].[0-9][0-9]"

env:
  N: transmission
  TD: _tarball
  BD: _build
  BT: RelWithDebInfo

jobs:
  Build_and_Release:
    runs-on: ubuntu-latest
    container: zscself/build_transmission_env
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Configure CMake (tarball)
      run: cmake -S . -B $TD -G Ninja -DCMAKE_BUILD_TYPE=$BT -DCPACK_SOURCE_IGNORE_FILES=$TD -DENABLE_CLI=ON
    - name: Build (tarball)
      run: cmake --build $TD --target package_source
    - name: Extract Package Source
      run: cmake -E tar xf $TD/$N-[0-9].[0-9][0-9]*.tar.xz
    - name: Configure CMake (bin)
      run: cmake -S $N-[0-9].[0-9][0-9]* -B $BD -G Ninja -DCMAKE_BUILD_TYPE=$BT -DENABLE_CLI=ON
    - name: Build (bin)
      run: cmake --build $BD --target package
    - name: Test
      run: cmake -E chdir $BD ctest --output-on-failure
    - name: Copy Artifacts
      run: |
        mkdir artifacts
        mv $TD/$N-[0-9].[0-9][0-9]*.tar.xz artifacts
        mv $BD/$N-*-Linux.sh artifacts
        mv $BD/$N-*-Linux.tar.* artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "artifacts/*"
